
# 2. Exercícios Numpy

Agora que aprendemos sobre o NumPy, vamos testar seu conhecimento. Começaremos com algumas tarefas simples e, em seguida, você terá algumas perguntas mais complicadas.

#### Import NumPy as np

In [6]:
import numpy as np

#### Create an array of 10 zeros 

In [7]:
in_array = []

in_array = np.zeros((10))
print(in_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### Create an array of 10 ones

In [8]:

in_array = []

in_array = np.ones((10))
print(in_array)



[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


#### Create an array of 10 fives

In [12]:
in_array = np.full((10), 5.)
print(np.array(in_array))

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


#### Create an array of the integers from 10 to 50

In [14]:
in_array = []

for x in xrange(10,51):
		in_array.append(x)
print(in_array)

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]


#### Create an array of all the even integers from 10 to 50

In [15]:
in_array = []
for x in xrange(10,51):
	if x%2 == 0 :
		in_array.append(x)
print(in_array)

[10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50]


#### Create a 3x3 matrix with values ranging from 0 to 8

In [17]:
my_matx = np.array([[0,1,2], [3,4,5], [6,7,8]])
print(my_matx)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Create a 3x3 identity matrix

In [18]:
my_matx = np.eye(3)         
print(my_matx) 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Use NumPy to generate a random number between 0 and 1

In [19]:
print(np.random.rand(1))


[0.26557363]


#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [22]:
np.random.randn(5,5)

array([[-0.24611461, -0.06076215,  1.22654449,  1.40707987, -2.0852042 ],
       [ 0.21152835,  0.69590739,  1.65784129,  1.23912838,  0.2699976 ],
       [-0.08414319,  0.66027767,  0.60415191,  0.25532839, -0.12468643],
       [-0.90875479,  0.7366275 ,  0.45625106,  0.44872468,  1.75540757],
       [-1.41562936, -0.86230282, -0.15769201,  0.91103233, -2.10295719]])

#### Create the following matrix:

In [40]:
a = (np.arange(1,101).reshape(10,10) / 100) #i testing with a round function but returned warnings
print(a)
#a = round((np.arange(1,101).reshape(10,10) / 100),2) #set 2 others decimal positions
#print(float(a))

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1]]


#### Create an array of 20 linearly spaced points between 0 and 1:

In [23]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [24]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [39]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [25]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [29]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [26]:
mat[3,4]

20

In [30]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [27]:
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [31]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [28]:
mat[4:,0:4]

array([[21, 22, 23, 24]])

In [32]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [29]:
mat[3:,0:4]

array([[16, 17, 18, 19],
       [21, 22, 23, 24]])

### Now do the following

#### Get the sum of all the values in mat

In [30]:
mat.sum()

325

#### Get the standard deviation of the values in mat

In [31]:
mat.std()

7.211102550927978

#### Get the sum of all the columns in mat

In [32]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

# Great Job!